name: Testing

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Code testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached npm dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: npm-dependencies-${{ hashFiles('yarn.lock') }}

      - run: yarn install --immutable

      - name: Cache npm dependencies
        id: cache-dependencies-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}

      - uses: nrwl/nx-set-shas@v3
      # - run: git branch --track main origin/main
      - run: yarn nx affected -t test

  e2e:
    name: End-to-end testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cached npm dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: npm-dependencies-${{ hashFiles('yarn.lock') }}

      - run: yarn install --immutable

      - name: Cache npm dependencies
        id: cache-dependencies-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}

      - uses: nrwl/nx-set-shas@v3
      # - run: git branch --track main origin/main
      - run: yarn nx affected -t e2e -c ci --parallel=1
